// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  mySidebar: [
    {
      type: "category",
      label: "Namaste JS Season 1",
      // Generates lecture-1 to lecture-19
      items: Array.from({ length: 19 }, (_, index) => `lecture-${index + 1}`),
    },
    {
      type: "category",
      label: "Namaste JS Season 2",
      // Generates lecture-20 to lecture-24
      items: Array.from({ length: 6 }, (_, index) => `lecture-${index + 20}`),
    },
  ],
};

module.exports = sidebars;
